!SESSION 2016-08-04 11:55:04.951 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /home/ymy/workspace/.metadata/.bak_0.log
Created Time: 2016-08-04 11:55:29.833

!ENTRY org.python.pydev.shared_core 1 1 2016-08-04 11:55:29.834
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-08-04 11:55:32.738
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-08-04 11:55:32.793
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-08-04 11:55:32.794
!MESSAGE . Command line: hg -y showconfig ui.username
!SESSION 2016-09-02 09:45:03.985 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-09-02 09:45:45.112
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-09-02 09:45:45.112
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.eclipse.equinox.app 4 2 2016-09-02 09:45:59.414
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.app".
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4361)
	at org.eclipse.swt.SWT.error(SWT.java:4276)
	at org.eclipse.swt.SWT.error(SWT.java:4247)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:480)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:417)
	at org.eclipse.swt.widgets.Shell.close(Shell.java:612)
	at org.eclipse.ui.splash.AbstractSplashHandler.dispose(AbstractSplashHandler.java:63)
	at org.eclipse.ui.splash.BasicSplashHandler.dispose(BasicSplashHandler.java:189)
	at org.eclipse.ui.internal.Workbench$9.applicationRunning(Workbench.java:775)
	at org.eclipse.equinox.internal.app.EclipseAppHandle$1.run(EclipseAppHandle.java:268)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.applicationRunning(EclipseAppHandle.java:258)
	at org.eclipse.core.internal.runtime.InternalPlatform.endSplash(InternalPlatform.java:163)
	at org.eclipse.core.runtime.Platform.endSplash(Platform.java:568)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2632)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-02 09:46:00.672
!MESSAGE It seems it's already disposed...
!STACK 0
java.lang.RuntimeException: It seems it's already disposed...
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_ui.outline.BaseModel.setRoot(BaseModel.java:183)
	at org.python.pydev.shared_ui.outline.BaseModel$1$1.run(BaseModel.java:66)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-02 09:46:00.719
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-02 09:46:00.720
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-02 09:46:00.721
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-09-02 09:46:08.260
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-09-02 09:46:08.507
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-09-02 09:46:08.510
!MESSAGE . Command line: hg -y showconfig ui.username
!SESSION 2016-09-14 10:41:51.045 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-09-14 10:42:13.248
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-09-14 10:42:13.248
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-14 10:42:13.798
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-14 10:42:13.866
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-14 10:42:13.867
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-09-14 10:42:15.334
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-09-14 10:42:15.496
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-09-14 10:42:15.497
!MESSAGE . Command line: hg -y showconfig ui.username
!SESSION 2016-09-21 17:07:36.334 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-09-21 17:08:03.119
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-09-21 17:08:03.119
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-21 17:08:06.860
!MESSAGE It seems it's already disposed...
!STACK 0
java.lang.RuntimeException: It seems it's already disposed...
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_ui.outline.BaseModel.setRoot(BaseModel.java:183)
	at org.python.pydev.shared_ui.outline.BaseModel$1$1.run(BaseModel.java:66)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-21 17:08:06.946
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-21 17:08:06.948
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-09-21 17:08:06.949
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-09-21 17:08:08.984
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-09-21 17:08:09.133
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-09-21 17:08:09.134
!MESSAGE . Command line: hg -y showconfig ui.username
!SESSION 2016-10-08 14:04:33.286 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-10-08 14:04:55.964
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-10-08 14:04:55.964
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-08 14:04:57.384
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-08 14:04:57.397
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-08 14:04:57.398
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-10-08 14:04:59.284
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-10-08 14:04:59.481
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-10-08 14:04:59.482
!MESSAGE . Command line: hg -y showconfig ui.username

!ENTRY org.eclipse.jface 2 0 2016-10-09 10:24:21.426
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-10-09 10:24:21.426
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
!SESSION 2016-10-18 10:05:58.628 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-10-18 10:06:21.487
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-10-18 10:06:21.487
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-18 10:06:24.251
!MESSAGE It seems it's already disposed...
!STACK 0
java.lang.RuntimeException: It seems it's already disposed...
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_ui.outline.BaseModel.setRoot(BaseModel.java:183)
	at org.python.pydev.shared_ui.outline.BaseModel$1$1.run(BaseModel.java:66)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-18 10:06:24.367
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-18 10:06:24.369
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-18 10:06:24.370
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-10-18 10:06:26.174
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-10-18 10:06:26.309
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-10-18 10:06:26.310
!MESSAGE . Command line: hg -y showconfig ui.username
!SESSION 2016-10-26 10:07:59.553 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-10-26 10:08:12.092
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-10-26 10:08:12.092
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:08:12.846
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:08:12.905
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:08:12.906
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 2 0 2016-10-26 10:08:13.086
!MESSAGE Batch size for status command not correct.

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-10-26 10:08:14.174
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-10-26 10:08:14.245
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-10-26 10:08:14.245
!MESSAGE . Command line: hg -y showconfig ui.username

!ENTRY org.eclipse.jface 2 0 2016-10-26 10:08:17.793
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-10-26 10:08:17.793
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-10-26 10:09:58.659
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1055)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1182)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:929)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:337)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:78)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:63)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:116)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:110)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:15:39.870
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:15:39.872
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:15:39.872
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:23:33.657
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:23:33.662
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-26 10:23:33.663
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:681)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-10-28 10:04:40.075
!MESSAGE It seems it's already disposed...
!STACK 0
java.lang.RuntimeException: It seems it's already disposed...
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_ui.outline.BaseModel.setRoot(BaseModel.java:183)
	at org.python.pydev.shared_ui.outline.BaseModel$1$1.run(BaseModel.java:66)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
!SESSION 2016-11-11 16:06:27.008 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2016-11-11 16:06:49.924
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-11-11 16:06:49.934
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-11-11 16:06:50.248
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-11-11 16:06:51.056
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-11-11 16:06:51.201
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-11-11 16:06:51.202
!MESSAGE . Command line: hg -y showconfig ui.username

!ENTRY org.eclipse.jface 2 0 2016-11-14 17:53:19.518
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-11-14 17:53:19.543
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
!SESSION 2016-11-15 11:24:24.227 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=zh_CN
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.python.pydev.shared_core 1 1 2016-11-15 11:24:44.781
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/PILcompat
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-11-15 11:24:44.877
!MESSAGE Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/lib/python2.7/dist-packages/ubuntu-sso-client
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 1 1 2016-11-15 11:24:44.878
!MESSAGE Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: /usr/local/lib/python2.7/dist-packages/pymongo-3.1.1-py2.7-linux-x86_64.egg
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:52)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:463)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:444)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:67)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:89)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.jface 2 0 2016-11-15 11:24:46.929
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-11-15 11:24:46.929
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,Capitalize,
		,
		Category(AnyEdit.category,AnyEdit Tools,AnyEdit Tools key bindings,true),
		de.loskutov.anyedit.actions.ChangeCase,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,Insert ChangeLog entry,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.linuxtools.internal.changelog.core.actions.InsertChangeLogKeyHandler,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY com.vectrace.MercurialEclipse 1 0 2016-11-15 11:24:46.996
!MESSAGE checking encoding (ascii)...
checking Python executable (/usr/bin/python)
checking Python version (2.7.12)
checking Python lib (/usr/lib/python2.7)...
checking installed modules (/usr/lib/python2.7/dist-packages/mercurial)...
checking templates (/usr/share/mercurial/templates)...
checking commit editor...
checking username...
no username found, using 'ymy@ymy-TravelMate-P238-M' instead
no problems detected

!ENTRY com.vectrace.MercurialEclipse 4 0 2016-11-15 11:24:47.383
!MESSAGE . Command line: hg -y showconfig ui.username, error code: 1
!STACK 1
. Command line: hg -y showconfig ui.username, error code: 1
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToStream(AbstractShellCommand.java:448)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToBytes(AbstractShellCommand.java:387)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:605)
	at com.vectrace.MercurialEclipse.commands.AbstractShellCommand.executeToString(AbstractShellCommand.java:601)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLines(HgConfigClient.java:30)
	at com.vectrace.MercurialEclipse.commands.HgConfigClient.getHgConfigLine(HgConfigClient.java:22)
	at com.vectrace.MercurialEclipse.team.MercurialUtilities.getDefaultUserName(MercurialUtilities.java:256)
	at com.vectrace.MercurialEclipse.preferences.PreferenceInitializer$1.run(PreferenceInitializer.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 com.vectrace.MercurialEclipse 4 1 2016-11-15 11:24:47.383
!MESSAGE . Command line: hg -y showconfig ui.username

!ENTRY org.eclipse.jface 2 0 2016-11-15 11:24:55.605
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-11-15 11:24:55.605
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
